
export const PeopleMockData = {
  getMockPeopleJson: () => {
    return JSON.stringify({
      id: 1,
      type: 'identity',
      created_at: '2023-12-20T10:30:00Z',
      updated_at: '2023-12-20T15:45:00Z',
      title: 'Crypto Enthusiast',
      identity_type: 'individual',
      bio:
        'Passionate about DeFi, NFTs, and the future of decentralized finance. Building the next generation of web3 applications.',
      display_picture: 'https://example.com/avatar.jpg',
      preferred_ens_name: 'johndoe.eth',
      username: 'johndoe',
      socials: {
        twitter: 'johndoe',
        discord: 'johndoe#1234',
        github: 'johndoe',
        website: 'https://johndoe.com',
        email: 'john@johndoe.com',
      },
      follower_count: {value: 1250, display_value: '1.2K'},
      following_count: {value: 89, display_value: '89'},
      twitter_follower_count: {value: 850, display_value: '850'},
      bundle: {
        address_infos: [
          {
            address: '0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6',
            chain: 'ethereum',
            chain_id: '1',
            address_type: 'wallet',
            display_name: 'Main Wallet',
            display_picture: 'https://example.com/wallet_icon.png',
            net_worth: {
              _Any: {
                total_usd_value: {value: 50000.0, display_value: '\$50K'},
              },
            },
          },
          {
            address: '0x1234567890123456789012345678901234567890',
            chain: 'polygon',
            chain_id: '137',
            address_type: 'wallet',
            display_name: 'Polygon Wallet',
            display_picture: 'https://example.com/polygon_icon.png',
            net_worth: {
              _Any: {
                total_usd_value: {value: 25000.0, display_value: '\$25K'},
              },
            },
          },
        ],
      },
      display_name: 'John Doe',
      name: 'John Doe',
      address: '0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6',
      profiles: {
        '0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6': {
          id: 1,
          display_name: 'John Doe',
          ens_name: 'johndoe.eth',
          bio: 'Crypto enthusiast and DeFi user',
          display_picture: 'https://example.com/avatar.jpg',
          address: '0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6',
          username: 'johndoe',
        },
      },
      net_worth: {
        _Any: {
          total_usd_value: {value: 75000.0, display_value: '\$75K'},
        },
        ethereum: {
          total_usd_value: {value: 50000.0, display_value: '\$50K'},
        },
        polygon: {
          total_usd_value: {value: 25000.0, display_value: '\$25K'},
        },
      },
      net_worth_preferences: [1, 137],
      is_twitter_profile_fetching: false,
      link: 'https://example.com/profile/johndoe',
      search_hints: {
        display_name: ['John', 'Doe', 'johndoe'],
        address: ['0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6'],
      },
      followed: false,
      is_follow_loading: false,
      address_chain: 'ethereum',
      ens_name: 'johndoe.eth',
      token_details: {
        logo: 'https://example.com/token_logo.png',
        name: 'John Doe Token',
        symbol: 'JDT',
        decimals: 18,
        market_cap: {value: 1000000.0, display_value: '\$1M'},
        header_image_uri: 'https://example.com/header_image.jpg',
        image_uri: 'https://example.com/token_image.png',
      },
      protocol_details: {
        icon: 'https://example.com/protocol_icon.png',
        name: 'John Doe Protocol',
        website: 'https://johndoe.com',
        link: 'https://johndoe.com',
        identifier: 'johndoe_protocol',
      },
      address_type: 'identity',
      active_since: '2021-03-15T00:00:00Z',
      aliases_list: ['johndoe', 'john_doe', 'crypto_john'],
      is_token: false,
      protocol_link: 'https://johndoe.com',
      is_follow_directly: false,
      is_user_account: true,
      notification_preference: 'all',
      is_edit_profile: false,
      user_since: '2021-03-15T00:00:00Z',
      identity_link: 'https://example.com/identity/1',
      is_loading: false,
      is_verified: true,
      stream_chat_details: {
        channel_id: 'identity_1',
        user_id: 'user_1',
        token: 'stream_token_123',
      },
      invited_by_details: {
        inviter_id: 2,
        inviter_name: 'Jane Smith',
        invitation_date: '2021-03-15T00:00:00Z',
      },
      banner_picture: 'https://example.com/banner.jpg',
      symbol: 'JDT',
      token_slug: 'john-doe-token',
      identities: {
        '1': {
          id: 1,
          display_name: 'John Doe',
          ens_name: 'johndoe.eth',
          address: '0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6',
        },
      },
      mutual_followers_info: '5 mutual followers',
      follow_of_follows: 'Followed by 12 people you follow',
      followers: [
        {
          id: 2,
          display_name: 'Jane Smith',
          ens_name: 'janesmith.eth',
          address: '0x9876543210987654321098765432109876543210',
          username: 'janesmith',
          display_picture: 'https://example.com/jane_avatar.jpg',
        },
        {
          id: 3,
          display_name: 'Bob Wilson',
          ens_name: 'bobwilson.eth',
          address: '0x1111111111111111111111111111111111111111',
          username: 'bobwilson',
          display_picture: 'https://example.com/bob_avatar.jpg',
        },
      ],
      collection_id: 'collection_123',
      is_user_profile: true,
      market_cap: {value: 1000000.0, display_value: '\$1M'},
      chain: 'ethereum',
      chain_id: '1',
      follower_source: ['twitter', 'discord', 'github'],
      search_tag: 'crypto_enthusiast',
      search_usd_value_info: {value: 75000.0, display_value: '\$75K'},
      total_usd_value: {value: 75000.0, display_value: '\$75K'},
      token_balance: {value: 1000.0, display_value: '1,000 JDT'},
      usd_price: {value: 75.0, display_value: '\$75.00'},
      user_follows_identity: {followed: false, follow_date: null},
      verified_socials: ['twitter', 'github'],
      onboarding_state: 'completed',
      volume24: {value: 50000.0, display_value: '\$50K'},
      change1h: {value: 2.5, display_value: '+2.5%', direction: 1},
      change24h: {value: 5.0, display_value: '+5.0%', direction: 1},
      floor_price: {value: 70.0, display_value: '\$70.00'},
      external_links: {
        twitter: 'https://twitter.com/johndoe',
        discord: 'https://discord.gg/johndoe',
        github: 'https://github.com/johndoe',
        website: 'https://johndoe.com',
      },
    });
  },
};
